language: go

go:
  - tip

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get golang.org/x/lint/golint
    - go get github.com/mattn/goveralls

install:
    - go get -t ./... && go build ./...

script:
    - go vet -x ./...
    - $GOPATH/bin/golint ./...
    - go test -v ./...
    - go test -covermode=count -coverprofile=profile.cov .

after_script:
    - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
    - go test -benchmem -bench .
